spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_management
    password: root
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

server:
  port: 9030

swagger:
  enabled: true
  servicename: catalog-service
  description: Catalog Management service
  version: 1.0
  basepakage: com.example.licious.inlo
  baseurl: "/.*"